edges:
  TRACKS:
    Delivery__Warehouse:
      properties:
        - method:String
        - tracking_number:String
      from: Delivery
      to: Warehouse
      median: 4
      sigma: 2

    Vehicle__Warehouse:
      properties:
        - vehicle_type:String
        - license_plate:String
      from: Vehicle
      to: Warehouse
      median: 2
      sigma: 1

  CONTAINS:
    Warehouse__Product:
      properties:
        - bin_location:String
        - stock_level:Int
      from: Warehouse
      to: Product
      median: 6
      sigma: 3

vertices:
  Delivery:
    properties:
      - startTime:Long
      - endTime:Long
      - origin:String
      - destination:String
      - isExpress:Bool
    percent: 25

  Vehicle:
    properties:
      - model:String
      - year:Int
      - capacity:Double
      - fuelType:String
      - active:Bool
    percent: 15

  Warehouse:
    properties:
      - location:String
      - area:Int
      - temperatureControlled:Bool
      - manager:String
    percent: 40

  Product:
    properties:
      - productCode:String
      - name:String
      - category:String
      - expirationDate:Long
    percent: 20
