EgoNode:
  label: "GoldenEntity"
  connections:
    Partner:
      median: 3
      sigma: 2
    Device:
      median: 1
      sigma: 2
    Cookie:
      median: 2
      sigma: 1
    PhoneNumber:
      median: 1
      sigma: 1.1
  properties:
    method:
      generator: pyint(min_value=1, max_value=5)
      type: int

    tracking_number:
      generator: pyint(min_value=1, max_value=5)
      type: int
AlterNodes:
  Partner:
    label: Partner
    properties:
      established:
        generator: date()
        type: date
      contracted:
        generator: pybool(0.8)
        type: bool
      teams:
        type: list
        element_type: string
        generator: pylist(nb_elements=15, allowed_types=[str])
    connections:
      Cookie:
        median: 2
        sigma: 1
      Device:
        median: 1
        sigma: 1.5
      PhoneNumber:
        median: 1
        sigma: 1
  Cookie:
    label: Cookie
    properties:
      website:
        type: string
        generator: company()
      idx:
        type: long
        generator: pyint(min_value=1000000000000, max_value=99999999999999)


  PhoneNumber:
    label: PhoneNumber
    properties:
      method:
        type: int
        prefer_unique: False
        generator: pyint(min_value=-2147483648, max_value=2147483647)
      tracking_number:
        type: long
        prefer_unique: True
        generator: pyint(min_value=10000000000, max_value=99999999999)
  Device:
    label: Device
    properties:
      type:
        type: String
        prefer_unique: false
        generator: pystr(min_chars=3, max_chars=12)
      last_accessed:
        type: date
        prefer_unique: false
        generator: date()
      use_per_day_hrs:
        type: double
        prefer_unique: false
        generator: pyfloat(min_value=-1e9, max_value=1e9)