version: "3"
services:
  aerospike-db:
    image: aerospike/aerospike-server-enterprise:7.1
    container_name: aerospike-db
    networks:
      - asgraph_net
    ports:
      - "3000-3002:3000-3002"
    environment:
      - DEFAULT_TTL=0
    healthcheck:
      test: ["CMD", "asinfo", "-p", "3000", "-v", "build"]
      interval: 30s
      timeout: 20s
      retries: 3
  aerospike-graph-service:
    image: aerospike/aerospike-graph-service:latest
    container_name:
      aerospike-graph-service
      #    restart: always
    depends_on:
      aerospike-db:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    ports:
      - "8182:8182"
      - "9090:9090"
    environment:
      - aerospike.client.namespace=test
      - aerospike.client.host=aerospike-db
      - aerospike.graph.index.vertex.label.enabled=true
      - aerospike.graph.query-tracing.threshold-ms=5
      - aerospike.graph.query-tracing.opentelemetry-host=zipkin
    volumes:
      - ./examples:/data
    networks:
      - asgraph_net
  zipkin:
    image: openzipkin/zipkin
    container_name:
      asgraph-zipkin
    networks:
      - asgraph_net
    ports:
      - "9411:9411"
      
networks:
  asgraph_net:
    name: asgraph_net
